"""init migrate

Revision ID: 89fb04008300
Revises: 
Create Date: 2020-12-02 13:25:29.708540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89fb04008300'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_clean_df_title', table_name='clean_df')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_clean_df_title', 'clean_df', ['title'], unique=False)
    # ### end Alembic commands ###
